---
- name: "Download latest wordpress"
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: '/tmp/wordpress.tar.gz'
 
- name: "Extract worpress.tar.gz"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www"
    remote_src: yes
  become: yes

- name: "Create wp-config.php"
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: "Configure database credentians in the wp-config.php"
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: "database_name_here", value: "{{ db_name }}" }
    - { regex: "username_here", value: "{{ db_username }}" }
    - { regex: "password_here", value: "{{ db_user_password }}" }
    - { regex: "localhost", value: "{{ db_ip }}" }
  become: yes
 
- name: "Configure wordpress site on apache2 server"
  template:
    src: "templates/wordpress.conf.j2"
    dest: "/etc/apache2/sites-available/wordpress.conf"
  become: yes
 
- name: "Enable wordpress site on apache server"
  shell: a2ensite wordpress
  become: yes
  notify:
    - restart apache
